#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/deploy-stack
- name: load secret variables
  include_vars:
    file: secret.yml

- name: create directory
  file:
    path: "/home/{{ ansible_user }}/wordpress-stack"
    state: directory
    mode: "0755"

- name: create volume to store data
  docker_volume:
    name: "{{ item }}"
    state: present
  loop:
    - wp_data
    - db_data

- name: push docker-compose file into wordpress-stack directory
  template:
    dest: "/home/{{ ansible_user }}/wordpress-stack/docker-compose.yml"
    src: docker-compose.yml.j2

- name: running docker compose
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/wordpress-stack/"
    state: present
  register: output

- name: check docker compose is running
  debug:
    var: output
