apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: "{{ app_namespace }}"
type: Opaque
stringData:
  MYSQL_DATABASE: "{{ mysql_database }}"
  MYSQL_USER: "{{ mysql_user }}"
  MYSQL_PASSWORD: "{{ mysql_password }}"
  MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
