apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-ci-sa
  namespace: drone
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: drone-ci-role
  namespace: drone
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","list","watch","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: drone-ci-rolebinding
  namespace: drone
subjects:
- kind: ServiceAccount
  name: drone-ci-sa
  namespace: drone
roleRef:
  kind: Role
  name: drone-ci-role
  apiGroup: rbac.authorization.k8s.io
---
#secret
apiVersion: v1
kind: Secret
metadata:
  name: drone-ci-secret
  namespace: drone
  annotations:
    kubernetes.io/service-account.name: "drone-ci-sa"
type: kubernetes.io/service-account-token
