#SPDX-License-Identifier: MIT-0
---
# tasks file for node-exporter
- name: create a directory for node-export docker compose
  file:
    path: "/home/{{ ansible_user }}/node-exporter"
    state: directory
    mode: "0755"

- name: copy docker compose file into directory
  template:
    src: docker-compose.yml.j2
    dest: "/home/{{ ansible_user }}/node-exporter/docker-compose.yml"

- name: run docker compose
  community.docker.docker_compose_v2:
    project_src: "/home/{{ ansible_user }}/node-exporter/"
    state: present
