kind: pipeline
type: docker
name: build-docker-image

steps:
  - name: check
    image: node:18
    commands:
      - npm install -g htmlhint
      - htmlhint app/index.html

#  - name: test-nginx-config
#    image: docker:dind
#    commands:
#      - dockerd-entrypoint.sh & # Khởi động Docker daemon trong background
#      - sleep 5 # Đợi Docker daemon khởi động
#      - docker run --rm -v $(pwd)/nginx.conf:/etc/nginx/nginx.conf:ro nginx:latest -t -c /etc/nginx/nginx.conf

  - name: build and publish
    image: plugins/docker
    settings:
      insecure: true
      repo: 192.168.1.105:5000/simple # Thay bằng tên repo bạn muốn trên Docker Hub
      registry: 192.168.1.105:5000
      #username:
        #from_secret: docker_username
      #password:
        #from_secret: docker_password
      tags:
        - latest
